# Generated by Django 3.0.8 on 2020-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contractor_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='instrument',
            new_name='main_instrument',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='generic-user.jpg', null=True, upload_to=''),
        ),
    ]
