# Generated by Django 3.0.8 on 2020-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200711_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='alumni',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='contractor',
            name='battery_amp',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='pa_system',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='contractor',
            name='public_liability',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='contractor',
            name='year_finished',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
