# Generated by Django 3.0.8 on 2020-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200711_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='alumni',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='battery_amp',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.CharField(default='Sydney', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='main_instrument',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='pa_system',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='public_liability',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='year_finished',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
