# Generated by Django 3.0.8 on 2020-07-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200711_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='alumni',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='battery_amp',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='pa_system',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='public_liability',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
    ]
