# Generated by Django 3.0.8 on 2020-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200711_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='alumni',
            field=models.CharField(blank=True, default='No', max_length=3),
        ),
    ]
