# Generated by Django 3.0.8 on 2020-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_contractor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.CharField(default='Sydney', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='public_liability',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
