# Generated by Django 3.0.8 on 2020-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200711_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='alumni',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='battery_amp',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='pa_system',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='year_finished',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
