# Generated by Django 3.0.8 on 2020-07-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200712_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
