# Generated by Django 3.0.8 on 2020-07-13 13:14

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_contractor_gst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='abn',
            field=models.IntegerField(null=True, validators=[users.validators.abn_validator]),
        ),
        migrations.AddField(
            model_name='contractor',
            name='accept_on_spot_requests',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contractor',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='bsb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='can_mc',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='meal_preference',
            field=models.CharField(blank=True, choices=[('standard', 'standard'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescetarian', 'Pescetarian'), ('gluten_free', 'Gluten Free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('dairy_free', 'Dairy Free')], default='standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='number_plate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='other_instruments',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='secondary_instrument',
            field=models.CharField(blank=True, choices=[('electric_bass', 'Electric Bass'), ('double_bass', 'Double Bass'), ('guitar', 'Guitar'), ('keys', 'Keys'), ('banjo', 'Banjo'), ('drums', 'Drums'), ('percussion', 'Percussion'), ('male_lead_vocals', 'Male Lead Vocals (For a whole gig)'), ('female_lead_vocals', 'Female Lead Vocals (For a whole gig)'), ('backing_vocals', 'Backing Vocals'), ('trumpet', 'Trumpet'), ('tenor_saxophone', 'Tenor Saxophone'), ('alto_saxophone', 'Alto Saxophone'), ('bari_saxophone', 'Baritone Saxophone'), ('soprano_saxophone', 'Soprano Saxophone'), ('trombone', 'Trombone'), ('sousaphone', 'Sousaphone'), ('violin', 'Violin'), ('viola', 'Viola'), ('cello', 'Cello'), ('oboe', 'Oboe'), ('cor_anglais', 'Cor Anglais'), ('harp', 'Harp'), ('sound_person', 'Sound Person'), ('dj', 'DJ')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='state',
            field=models.CharField(choices=[('nsw', 'NSW'), ('vic', 'VIC'), ('act', 'ACT'), ('qld', 'QLD'), ('nt', 'NT'), ('wa', 'WA'), ('sa', 'SA')], default='NSW', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.CharField(choices=[('sydney', 'Sydney'), ('melbourne', 'Melbourne'), ('adelaide', 'Adelaide'), ('brisbane', 'Brisbane'), ('canberra', 'Canberra'), ('gold_coast', 'Gold Coast')], default='Sydney', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='main_instrument',
            field=models.CharField(blank=True, choices=[('electric_bass', 'Electric Bass'), ('double_bass', 'Double Bass'), ('guitar', 'Guitar'), ('keys', 'Keys'), ('banjo', 'Banjo'), ('drums', 'Drums'), ('percussion', 'Percussion'), ('male_lead_vocals', 'Male Lead Vocals (For a whole gig)'), ('female_lead_vocals', 'Female Lead Vocals (For a whole gig)'), ('backing_vocals', 'Backing Vocals'), ('trumpet', 'Trumpet'), ('tenor_saxophone', 'Tenor Saxophone'), ('alto_saxophone', 'Alto Saxophone'), ('bari_saxophone', 'Baritone Saxophone'), ('soprano_saxophone', 'Soprano Saxophone'), ('trombone', 'Trombone'), ('sousaphone', 'Sousaphone'), ('violin', 'Violin'), ('viola', 'Viola'), ('cello', 'Cello'), ('oboe', 'Oboe'), ('cor_anglais', 'Cor Anglais'), ('harp', 'Harp'), ('sound_person', 'Sound Person'), ('dj', 'DJ')], max_length=100, null=True),
        ),
    ]
