# Generated by Django 3.0.8 on 2020-07-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_contractor_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='events',
        ),
    ]
