# Generated by Django 3.0.8 on 2020-07-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_contractor_denylisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
