# Generated by Django 3.0.8 on 2020-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booker',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booker',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
