# Generated by Django 3.0.8 on 2020-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookers', '0002_auto_20200715_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='booker',
            name='profile_picture',
            field=models.ImageField(blank=True, default='generic-user.jpg', null=True, upload_to=''),
        ),
    ]
