# Generated by Django 3.0.8 on 2020-07-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=30)),
                ('call_time', models.CharField(max_length=30)),
                ('fee_incl_gst', models.IntegerField()),
                ('bandleader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='events.Contractor')),
            ],
        ),
    ]
