# Generated by Django 3.0.8 on 2020-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_contractor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='instrument',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
