# Generated by Django 3.0.8 on 2020-07-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_contractor_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bandleader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Contractor'),
        ),
    ]
