# Generated by Django 3.0.8 on 2020-07-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200705_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='instrument',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
