# Generated by Django 3.0.8 on 2020-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200706_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='instrument',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
