# Generated by Django 3.0.8 on 2020-07-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0007_auto_20200706_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bandleader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='users.Contractor'),
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
