# Generated by Django 3.0.8 on 2020-07-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200713_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
