# Generated by Django 3.0.8 on 2020-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200713_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_complete',
            field=models.BooleanField(default=False),
        ),
    ]
