# Generated by Django 3.0.8 on 2020-07-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_event_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bandleader_base_fee',
            field=models.IntegerField(null=True),
        ),
    ]
