# Generated by Django 3.0.8 on 2020-07-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_bandleader_base_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee_incl_gst',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
