# Generated by Django 3.0.8 on 2020-07-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200713_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee_incl_gst',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
