# Generated by Django 3.0.8 on 2020-07-15 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookers', '0001_initial'),
        ('events', '0019_auto_20200713_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bookers.Booker'),
        ),
    ]
