# Generated by Django 3.0.8 on 2020-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200715_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
