# Generated by Django 3.0.8 on 2020-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20200715_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='call_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tax',
        ),
        migrations.AddField(
            model_name='event',
            name='asked_musicians',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='balance_and_surcharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='balance_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='band_lineup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='band_locked_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='booker_fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='booker_payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='business_payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='calendar_event_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='card_type',
            field=models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='client_followup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contract_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contract_signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='credit_card_surcharge_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='crew_meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit_and_surcharge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit_required',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='do_not_play',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_completion_status',
            field=models.CharField(blank=True, choices=[('awaiting_balance', 'Awaiting Balance'), ('awaiting_balance_and_deposit', 'Awaiting Balance and Deposit'), ('awaiting_musician_invoices', 'Awaiting Musician Invoices'), ('awaiting_balance', 'Cancelled'), ('postponed', 'Postponed'), ('complete', 'Complete')], default='Awaiting Balance and Deposit', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(blank=True, choices=[('locked_in', 'Locked in'), ('locked_in_via_email', 'Locked In Via Email'), ('tentative', 'Tentative')], default='Tentative', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='further_musician_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='general_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gig_source',
            field=models.CharField(blank=True, choices=[('word_of_mouth', 'Word Of Mouth'), ('general', 'General'), ('usyd', 'USYD'), ('website', 'Website'), ('busking', 'Busking')], default='Word Of Mouth', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='helpful_files',
            field=models.FileField(blank=True, null=True, upload_to='event_uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='important_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='invoice_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='loading_zone_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='musical_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='musician_only_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='musicians_attire',
            field=models.CharField(blank=True, default='Smart Casual', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='musicians_call_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='number_parking_spots_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_assignment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_cost_per_car',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_provided',
            field=models.CharField(blank=True, default='Not Required', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('direct_deposit', 'Direct Deposit'), ('poli', 'POLI'), ('credit_card', 'Credit Card'), ('cash', 'Cash')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='power_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='production',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rehearsal',
            field=models.CharField(blank=True, default='Not Required', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='run_sheet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_fee_incl_all',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_fee_incl_gst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_fee_no_gst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_gst_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='unavailable_musicians',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_in_case_of_rain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='New Event', max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
