# Generated by Django 3.0.8 on 2020-07-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20200715_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bandleader_base_fee',
            new_name='bandleader_fee',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fee_incl_gst',
        ),
        migrations.AddField(
            model_name='event',
            name='bandleader_fee_all_incl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bandleader_feedback_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bandleader_gst_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bandleader_invoice_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bandleader_payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
