# Generated by Django 3.0.8 on 2020-07-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20200716_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bandleader',
        ),
    ]
