# Generated by Django 3.0.8 on 2020-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_contractor_events'),
        ('events', '0026_remove_event_bandleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='musicians',
            field=models.ManyToManyField(to='users.Contractor'),
        ),
    ]
