# Generated by Django 3.0.8 on 2020-07-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_contractor_events'),
        ('events', '0027_event_musicians'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='musicians',
        ),
        migrations.AddField(
            model_name='event',
            name='musicians',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EventMusicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Contractor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
