# Generated by Django 3.0.8 on 2020-07-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20200716_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmusicians',
            name='instrument',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parking_address',
            field=models.CharField(blank=True, default='Near Venue', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parking_provided',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='run_sheet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
