# Generated by Django 3.0.8 on 2020-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20200721_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmusicians',
            name='feedback_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='eventmusicians',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='eventmusicians',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
    ]
