# Generated by Django 3.0.8 on 2020-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20200721_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='balance_paid',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='band_locked_in',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar_event_created',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='client_followup',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract_sent',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract_signed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deposit_paid',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_complete',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_completion_status',
            field=models.CharField(blank=True, choices=[('awaiting_balance', 'Awaiting Balance'), ('awaiting_balance_and_deposit', 'Awaiting Balance and Deposit'), ('awaiting_musician_invoices', 'Awaiting Musician Invoices'), ('awaiting_balance', 'Cancelled'), ('postponed', 'Postponed'), ('complete', 'Complete')], default='awaiting_balance_and_deposit', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(blank=True, choices=[('locked_in', 'Locked in'), ('locked_in_via_email', 'Locked In Via Email'), ('tentative', 'Tentative')], default='tentative', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='invoice_sent',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('direct_deposit', 'Direct Deposit'), ('poli', 'POLI'), ('credit_card', 'Credit Card'), ('cash', 'Cash')], default='direct_deposit', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_fee_no_gst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventmusicians',
            name='fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventmusicians',
            name='fee_all_incl',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventmusicians',
            name='gst_amnt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventmusicians',
            name='is_bandleader',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4, null=True),
        ),
    ]
