# Generated by Django 3.0.8 on 2020-07-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20200722_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmusicians',
            name='is_available',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
