# Generated by Django 3.0.8 on 2020-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20200727_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_parking_spots_required',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parking_cost_per_car',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
