# Generated by Django 3.0.8 on 2020-07-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20200727_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmusicians',
            name='email_invite_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
