# Generated by Django 3.0.8 on 2020-07-29 03:05

from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_event_email_worksheet_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmusicians',
            name='inclusions',
            field=models.FloatField(default=0, null=True, validators=[events.validators.fee_positive_validator]),
        ),
    ]
