# Generated by Django 3.0.8 on 2020-07-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='general_info',
            field=models.TextField(default=''),
        ),
    ]
