# Generated by Django 3.0.8 on 2020-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='general_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
